const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const path = require("path");
const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static(path.join(__dirname, "public")));
const rooms = {};
const WORDS = ["apple","house","car","tree","computer","phone","dog","cat","pizza","rocket","football","school","book","flower","mountain","river","chair","table"];
function generateRoomId(){return Math.random().toString(36).substring(2,8).toUpperCase()}
function normalizeSettings(s={}){return{maxPlayers:Math.min(20,Math.max(2,Number(s.maxPlayers)||10)),rounds:Math.min(10,Math.max(2,Number(s.rounds)||3)),drawTime:Math.min(240,Math.max(15,Number(s.drawTime)||60)),wordChoices:Math.min(5,Math.max(1,Number(s.wordChoices)||3)),hints:Math.min(5,Math.max(0,Number(s.hints)||3))}}
function getWordChoices(count){const pool=[...WORDS],choices=[];while(choices.length<count&&pool.length)choices.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);return choices}
function createMaskedWord(word,revealed){return word.split("").map((c,i)=>revealed.includes(i)?c:"_").join(" ")}
function updatePlayers(id){const r=rooms[id];if(r)io.to(id).emit("players_updated",r.players.map(p=>({id:p.id,name:p.name,score:p.score})))}
function sendLobby(id){const r=rooms[id];if(r)io.to(id).emit("lobby_state",{hostId:r.hostId,settings:r.settings,round:r.round,totalRounds:r.settings.rounds,playerCount:r.players.length})}
function revealHint(id){const r=rooms[id];if(!r||!r.gameStarted||!r.word)return;const a=[];for(let i=0;i<r.word.length;i++)if(!r.revealedPositions.includes(i)&&r.word[i]!==" ")a.push(i);if(!a.length)return;const pos=a[Math.floor(Math.random()*a.length)];r.revealedPositions.push(pos);io.to(id).except(r.drawerId).emit("hint_update",{wordLength:r.word.length,maskedWord:createMaskedWord(r.word,r.revealedPositions),hintsRevealed:r.revealedPositions.length,lettersLeft:r.word.replace(/ /g,"").length-r.revealedPositions.length})}
function startRound(id){const r=rooms[id];if(!r||r.players.length<2||r.round>r.settings.rounds)return;if(r.timer)clearInterval(r.timer);r.gameStarted=false;r.selectingWord=true;r.timeLeft=r.settings.drawTime;r.word="";r.wordChoices=getWordChoices(r.settings.wordChoices);r.revealedPositions=[];r.strokes=[];r.drawerIndex=(r.drawerIndex+1)%r.players.length;r.drawerId=r.players[r.drawerIndex].id;io.to(id).emit("game_started",{drawerId:r.drawerId,selecting:true,round:r.round,totalRounds:r.settings.rounds});io.to(r.drawerId).emit("word_options",{options:r.wordChoices});io.to(id).except(r.drawerId).emit("word_waiting",{message:"🎨 The drawer is choosing a word..."});sendLobby(id)}
function beginChosenWord(id,word){const r=rooms[id];if(!r||!r.selectingWord||!r.wordChoices.includes(word))return;r.word=word;r.selectingWord=false;r.gameStarted=true;r.timeLeft=r.settings.drawTime;r.revealedPositions=[];r.strokes=[];io.to(id).emit("word_chosen",{wordLength:r.word.length,round:r.round,totalRounds:r.settings.rounds});io.to(id).except(r.drawerId).emit("hint_update",{wordLength:r.word.length,maskedWord:createMaskedWord(r.word,[]),hintsRevealed:0,lettersLeft:r.word.replace(/ /g,"").length});io.to(id).emit("timer_update",r.timeLeft);r.timer=setInterval(()=>{r.timeLeft--;io.to(id).emit("timer_update",r.timeLeft);const interval=Math.max(1,Math.floor(r.settings.drawTime/(r.settings.hints+1)));if(r.settings.hints>0&&r.timeLeft>0&&r.timeLeft%interval===0&&r.revealedPositions.length<r.settings.hints)revealHint(id);if(r.timeLeft<=0)endRound(id)},1000)}
function endRound(id){const r=rooms[id];if(!r)return;if(r.timer){clearInterval(r.timer);r.timer=null}r.gameStarted=false;r.selectingWord=false;io.to(id).emit("round_ended",{word:r.word});if(r.round>=r.settings.rounds){setTimeout(()=>endGame(id),1800);return}r.round++;setTimeout(()=>{if(rooms[id]&&rooms[id].players.length>=2)startRound(id)},2500)}
function endGame(id){const r=rooms[id];if(!r)return;const leaderboard=[...r.players].sort((a,b)=>b.score-a.score);io.to(id).emit("game_over",{leaderboard:leaderboard.map(p=>({name:p.name,score:p.score,id:p.id})),winner:leaderboard[0]||null});r.gameStarted=false;r.selectingWord=false}
function startGame(id){const r=rooms[id];if(!r||r.players.length<2||r.hostId===null||r.gameStarted||r.selectingWord)return;r.round=1;startRound(id)}
io.on("connection",socket=>{
 socket.on("create_room",({playerName,settings}={})=>{let id=generateRoomId();while(rooms[id])id=generateRoomId();const s=normalizeSettings(settings);rooms[id]={players:[{id:socket.id,name:String(playerName||"Player").trim().slice(0,18),score:0}],hostId:socket.id,settings:s,round:0,gameStarted:false,selectingWord:false,drawerIndex:-1,drawerId:null,word:"",wordChoices:[],timeLeft:0,timer:null,revealedPositions:[],strokes:[]};socket.join(id);socket.roomId=id;socket.playerName=playerName;socket.emit("room_created",id);updatePlayers(id);sendLobby(id)});
 socket.on("join_room",({roomId,playerName})=>{const id=String(roomId||"").trim().toUpperCase(),r=rooms[id];if(!r)return socket.emit("room_error","Room not found");if(r.players.length>=r.settings.maxPlayers)return socket.emit("room_error",`Room is full (maximum ${r.settings.maxPlayers} players)`);if(r.gameStarted||r.selectingWord)return socket.emit("room_error","A game is already in progress");r.players.push({id:socket.id,name:String(playerName||"Player").trim().slice(0,18),score:0});socket.join(id);socket.roomId=id;socket.playerName=playerName;socket.emit("room_joined",id);updatePlayers(id);sendLobby(id)});
 socket.on("start_game",({roomId,settings})=>{const r=rooms[roomId];if(!r||socket.id!==r.hostId)return;r.settings=normalizeSettings(settings);if(r.players.length>r.settings.maxPlayers)return socket.emit("room_error",`Remove players first: the new maximum is ${r.settings.maxPlayers}`);startGame(roomId)});
 socket.on("choose_word",({roomId,word})=>{const r=rooms[roomId];if(r&&socket.id===r.drawerId)beginChosenWord(roomId,String(word))});
 socket.on("drawing_start",({roomId,x,y,color,size})=>{const r=rooms[roomId];if(!r||!r.gameStarted||socket.id!==r.drawerId)return;const stroke={color:color||"#111111",size:Number(size)||5,points:[{x,y}]};r.strokes.push(stroke);socket.to(roomId).emit("drawing_start",{x,y,color:stroke.color,size:stroke.size})});
 socket.on("drawing",({roomId,x,y,color,size})=>{const r=rooms[roomId];if(!r||!r.gameStarted||socket.id!==r.drawerId)return;const stroke=r.strokes[r.strokes.length-1];if(!stroke)return;stroke.points.push({x,y});socket.to(roomId).emit("drawing",{x,y,color:color||stroke.color,size:Number(size)||stroke.size})});
 socket.on("undo_drawing",({roomId})=>{const r=rooms[roomId];if(!r||!r.gameStarted||socket.id!==r.drawerId||!r.strokes.length)return;r.strokes.pop();io.to(roomId).emit("canvas_redraw",{strokes:r.strokes})});
 socket.on("clear_canvas",({roomId})=>{const r=rooms[roomId];if(!r||!r.gameStarted||socket.id!==r.drawerId)return;r.strokes=[];io.to(roomId).emit("canvas_clear")});
 socket.on("send_message",({roomId,playerName,message})=>{const r=rooms[roomId];if(!r)return;message=String(message).trim();if(!message)return;if(r.gameStarted&&socket.id!==r.drawerId&&message.toLowerCase()===r.word.toLowerCase()){const p=r.players.find(x=>x.id===socket.id);if(p)p.score+=10;io.to(roomId).emit("receive_message",{playerName:"🎯 SYSTEM",message:`${playerName} guessed correctly!`});updatePlayers(roomId);endRound(roomId);return}io.to(roomId).emit("receive_message",{playerName,message})});
 socket.on("disconnect",()=>{const id=socket.roomId,r=rooms[id];if(!r)return;r.players=r.players.filter(p=>p.id!==socket.id);if(r.timer){clearInterval(r.timer);r.timer=null}if(socket.id===r.hostId){r.hostId=r.players[0]?.id||null;if(r.hostId)io.to(id).emit("host_changed",{hostId:r.hostId})}updatePlayers(id);sendLobby(id);if(!r.players.length)delete rooms[id];else if(r.players.length<2){r.gameStarted=false;r.selectingWord=false;io.to(id).emit("word_waiting",{message:"Waiting for another player..."})}});
});
const PORT=process.env.PORT||3000;server.listen(PORT,"0.0.0.0",()=>console.log(`🎨 Skribbl Clone running on port ${PORT}`));
